use `pollster::block_on` instead of `futures::executor::block_on` (#2)
to avoid runtime error due to nested executor.

With the latter we get:

```
  thread 'main' panicked at /home/basti/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-executor-0.3.31/src/local_pool.rs:81:26:
  cannot execute `LocalPool` executor from within another executor: EnterError
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  failures:
      test_e2e

  test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 96.83s

  error: test failed, to rerun pass `--test e2e`
```